Feature: Olive 3 t-Sheet
#https://docs.google.com/a/essencedigital.com/spreadsheets/d/1QSetLFGCh6UkTKw5vZiwcKcGlyfqhOhJM-3u6wZq0KI/edit#gid=1531004265
In order to map olive 2 placements to Olive 3 financial data
As Campaign Manager
I want to be able to upload a new format T-sheet in Olive 2

#TO REVIEW
#in Olive 3
Scenario: Download O3 Plan with Line IDs for T-sheet (OTD-1921)
  Given I have set up a Media Plan in Olive 3
    And I have published it
  When I view the published version of the plan
  Then I can download a csv of all lines contianing the following columns:
#    -------------------------------------------------
#    |Client Name  |Campaign ID    |Campaign Name  |
#    |Media Plan ID|Media Plan Name|Initiative     |Market (code)|Start Date |End Date   |
#    |Plan Line ID |Section        |Supplier       |Property     |Platform   |Channel    |
#    |Media Type   |Currency       |Budget         |Description  |

#TO REVIEW
#in Olive 2
Scenario: New Format T-Sheet
  Given Campaign financial information is due to be managed thorugh Olive 3 as of new quarter
    And the plan and all lines are set up and published in Olive 3
    And Media Detail (T-sheet) relating to that plan is ready to be trafficked
  When AdOps member log into Olive 2
  Then he can find an upload form that accepts a new format T-sheet with the following changes:
#      ----------------------------------------------------------------------------------------------
#      |Campaign ID                    | PO ID     | Media Plan ID          | Plan Line ID          |
#      ----------------------------------------------------------------------------------------------
#      |Olive 2 Campaign ID (optional) | *REMOVE*  | Olive 3 Media Plan ID  | Olive 3 Plan Line ID  |
#      ----------------------------------------------------------------------------------------------
    And it is clearly labelled as "Olive 3 T-Sheet" (TBC)
    And on upload Olive 2 validates the T-Sheet format to ensure all columns are there
    And Olive 2 validates the content of new columns and displays feedback if failed:
#       ------------------------------------------------------------------------------------------------------------------------------
#       | RULE                                                         | Error Msg                                                   |
#       ------------------------------------------------------------------------------------------------------------------------------
#       | If Campaign ID provided, it's a recognised Olive 2 Campaign  | "Campaign ID not recognised"                                |
#       | If Campaign ID not provided, allow upload anyway             |                                                             |
#       | Plan Line ID is a recognised Olive 3 published plan line     | "Plan Line ID not recognised. Please ensure it's pubished"  |
#       | Media Plan ID is a recognised Olive 3 Pulbisehd Media Plan ID| "Media Plan ID not recognised. Please ensure it's published"|
#       | Plan Line belongs to Media Plan                              | "Plan Line belongs to a different Media Plan.               |
#       |                                                              | Please ensure IDs are correct"                              |

#TO REVIEW
Scenario: Olive 2 Campaign Doesn't exist
  Given a new O3 style t-sheet has been prepared for a completely new campaign (Trafic not set up) ()
  When Campaign Manager uploads Olive 3 T-sheet without any Olive 2 Campaign IDs
  Then Olive 2 validates the T-Sheet format to ensure all columns are there
    And Olive 2 validates the content
    And Olive 2 T-Sheet upload generates Campaigns, Budget Periods and Purchase Orders from Information

#TO FLESH OUT
Scenario: Olive 2 Budget Period doesn't exist but Placements, Bookings and Campaign already set up and trafficked in the previous quarter

#TO FLESH OUT
Scenario: Olive 2 Campaign already has a Budget Period that overlaps dates of O3 Media Plan in uploaded t-sheet
   - throw error asking to delete

#TO FLESH OUT
Scenario: Olive 3 autogenerated Olive 2 entities cannot be edited in Olive 2
