Feature: Add IO Meta Data

In order to support financial reporting needs
As Campaign Manager or IO Owner
I want to add certain meta data about Insertion Orders in Olive

#to review
Scenario: Specify Management Level (OTD-1974)
  #In order to calculate the correct fee that should be charged
  Given an insertion Order has been autogenerated as a result of adding a plan line to media plan
#    Or I have manually added a new Insertion Order
  When I view and edit details of the IO
  Then I can specify "Management Level" associated with the IO
    And I can choose one of the following Options: [All, Significant, Minor]
    And I can see a tooltip associated with field and
    # ALL -  actively manage all areas of House Ad activity
    # SIGNIFICANT - possess a significant role in managing activity, for example strategy, analysis, bespoke reporting or complex ad operations
    # MINOR - possess a minor role in managing activity, for example basic ad operations or summary reporting, usually budgets are "Unknown"
    And by default all known budget IOs are set to "All"
    And by default all "unknown budget" IOs are set to "Minor"
